execution_config:
  run_type: All   # Sanity / Functional / All
 
testcases:
 
  # ---- S3 File Check ----
  - rule_type: table_exists
    test_type: Sanity
    enabled: true
    object_name: "UDX_CORE.ERR.UOR_GALAXY_GENERATED_STATEMENTS_ERROR"
    parameters:

 
  # ---- Source vs Target Count ----
  - rule_type: count_check
    test_type: Functional
    enabled: true
    object_name: "RAW_DB.STAGE_SCHEMA.SOURCE_TABLE"
    parameters:
      target_table: "CURATED_DB.PROD_SCHEMA.TARGET_TABLE"
      filter_condition: "load_date = CURRENT_DATE"
 
  # ---- Null Check ----
  - rule_type: null_check
    test_type: Functional
    enabled: False
    object_name: "CURATED_DB.PROD_SCHEMA.CUSTOMER_TABLE"
    parameters:
      column_name: "CUSTOMER_ID"
 
  # ---- Duplicate Check ----
  - rule_type: duplicate_check
    test_type: Functional
    enabled: true
    object_name: "CURATED_DB.PROD_SCHEMA.ORDER_TABLE"
    parameters:
      column_name: "ORDER_ID"